<?php
declare(strict_types=1);

namespace Pixelant\PxaPmImporter\Validation;

/**
 * Hold result of validation
 *
 * @package Pixelant\PxaPmImporter\Validation
 */
class ValidationResult
{
    /**
     * @var bool
     */
    protected $passed = true;

    /**
     * Error message
     *
     * @var string
     */
    protected $error = '';

    /**
     * Property that was validated
     *
     * @var string
     */
    protected $property = '';

    /**
     * Name of validator that thrown an error
     *
     * @var string
     */
    protected $validatedBy = '';

    /**
     * @return bool
     */
    public function passed(): bool
    {
        return $this->passed;
    }

    /**
     * @param bool $passed
     */
    public function setPassed(bool $passed): void
    {
        $this->passed = $passed;
    }

    /**
     * @return string
     */
    public function getError(): string
    {
        return $this->error;
    }

    /**
     * @param string $error
     */
    public function setError(string $error): void
    {
        $this->error = $error;
    }

    /**
     * @return string
     */
    public function getProperty(): string
    {
        return $this->property;
    }

    /**
     * @param string $property
     */
    public function setProperty(string $property): void
    {
        $this->property = $property;
    }

    /**
     * Check if given results was generated by given validator
     *
     * @param string $validator
     * @return bool
     */
    public function isValidateBy(string $validator): bool
    {
        return $this->validatedBy === $validator;
    }

    /**
     * @return string
     */
    public function getValidatedBy(): string
    {
        return $this->validatedBy;
    }

    /**
     * @param string $validatedBy
     */
    public function setValidatedBy(string $validatedBy): void
    {
        $this->validatedBy = $validatedBy;
    }
}
